services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

  frontend:
    build:
      context: ./front
    ports:
      - "3000:80"
    depends_on:
      - gateway-service

  eureka-server:
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"

  gateway-service:
    build:
      context: ./gateway-service
    ports:
      - "8000:8000"
    depends_on:
      - user-service
      - eureka-server

  user-service:
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server

  chat-service:
    build:
      context: ./chat-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server

  board-service:
    build:
      context: ./board-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server

  alarm-service:
    build:
      context: ./alarm-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server

  kafka:
    image: bitnami/kafka:4.0.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/data
      ALLOW_PLAINTEXT_LISTENER: yes
    volumes:
      - kafka-data:/bitnami/kafka

volumes:
  grafana-storage:
  kafka-data:
